### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by grant**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [x] other

Use `master` License: https://github.com/socketio/socket.io/blob/master/LICENSE

### CODE REVIEW

**Comment by bodorjzsolt** [comment]
I am planning to use previous versions, does MIT License applies to older version also?

**Comment by grant** [comment]
No. The project states BSD for the previous version and this changes it to MIT.
I do not maintain this projects, so please contact the maintainer for further questions.

**Comment by bodorjzsolt** [comment]
Could you say what BSD was it exactly?

**Comment by grant** [comment]
Please ask the maintainer of this project, not me anymore. I don't have permissions for this project.

**Comment by grant** [comment]
@darrachequesne Can you look at this?

**Comment by darrachequesne** [comment]
LGTM :+1:

**Comment by WioSwitch** [comment]
🍎🍎🍎🍎🍎

**Pull request merged**
