### PR TITLE
Add package-lock.json to .gitignore

### PR DESCRIPTION
**Pull request by flaambe**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [x] other

### CODE REVIEW

**Comment by eltharynd** [comment]
it that not discouraged by npm devs?
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by flaambe** [comment]
Yeah i know, but I thought if the members do not want to commit ```package-lock.json```, it would be better to ignore it. @eltharynd

**Comment by dasilvacontin** [comment]
LGTM

**Comment by darrachequesne** [comment]
Let's add a package-lock file! Closed by https://github.com/socketio/socket.io/commit/1238ddb9951d3dd4414d03d6f68f3d3ba24eec1a.

**Pull request closed without merging**
