### PR TITLE
Add 'Features' section in the README

### PR DESCRIPTION
**Pull request by darrachequesne**
### The kind of change this PR does introduce

* an update to the documentation

Related: https://github.com/socketio/socket.io/issues/2823

### CODE REVIEW

**Comment by raulferras** [comment]
👍

**Comment by darrachequesne** [comment]
@raulferras thanks for the feedback! What I meant by that is that since `Socket.IO` does add some metadata to each packet (i.e. the packet type, the namespace, or the ack id when a message acknowledgement is needed), it will not be able to communicate with someone not talking the same "language". I'll try to rephrase that properly.

**Comment by raulferras** [comment]
Thanks to you @darrachequesne, now is much more clear ;)

**Comment by darrachequesne** [comment]
@raulferras again, thanks for the feedback!

**Pull request merged**
