### PR TITLE
Use fs.readFileSync instead of require.resolve

### PR DESCRIPTION
**Pull request by a-lucas**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [x] other

### Current behaviour

Browserify doesn't supports require.resolve, and as a consequence, makes nexe fails the compilation : 

### New behaviour

This PR attempts to read the content of the socket.io-client file via fs.readFileSync and falls back to the original require.resolve if this file cannot be found. 

### Other information (e.g. related issues)

https://github.com/nexe/nexe/issues/289

### CODE REVIEW

**Comment by darrachequesne** [comment]
Hi, thanks for the PR! How about using the following:

```js
function resolvePath(file){
  var filepath = path.resolve(__dirname, './../../', file);
  if (exists(filepath)) {
    return filepath;
  }
  return require.resolve(file);
}
```
Can you confirm the client file gets properly served that way? (you can also disable serving the client file with `serveClient: false`)

**Comment by darrachequesne** [comment]
Else, [brfs](https://github.com/substack/brfs) may be helpful here, if you actually want to serve the file.

**Comment by a-lucas** [comment]
@darrachequesne I never heard of brfs before, I also reckon your first suggestion is the best one, much DRYer, and also it doesn't requires an additional dependency.

Yes it works, [nexe](https://github.com/nexe/nexe) works great with socket.io with this change.

**Comment by darrachequesne** [comment]
Thanks!

**Comment by a-lucas** [comment]
Thanks too! Socket.io is great!

**Comment by khuongduybui** [comment]
Has this been released? I'm using socket.io 2.0.4 and is still plagued with "require.resolve" calls.

**Comment by Bolandish** [comment]
I'm also getting this error..

**Pull request merged**
