### PR TITLE
Allowing a custom function for opts.allowRequest

### LINKED ISSUE #2050: opts.allowRequest can no longer be custom
Before commit 463d7a16a139981f1eead005b388f720be0989bd, it was possible to pass a custom allowRequest function to socket.io. That commit added the `checkRequest` function, and always set `opts.allowRequest = this.checkRequest.bind(this);`, thus overwriting the passed in value. 

https://github.com/Automattic/socket.io/blob/master/lib/index.js#L225

Seems like it should be `opts.allowRequest = opts.allowRequest || this.checkRequest.bind(this);`.

### PR DESCRIPTION
**Pull request by tobalsgithub**
Fixes #2050

### CODE REVIEW

**Comment by TomKaltz** [comment]
+1

**Comment by rogermadjos** [comment]
+1

**Comment by TomKaltz** [comment]
Any update on why this can't be merged?

**Comment by leedm777** [comment]
:+1:

**Comment by artushin** [comment]
+1

**Comment by tobalsgithub** [comment]
It's been a number of months since this PR was submitted. Can someone take a look at it?

**Comment by luislobo** [comment]
+1

**Comment by tobalsgithub** [comment]
@rauchg, you're the only person I'm seeing doing anything with socket.io stuff recently. Any chance you can take a look at this? Or has active development stopped for some reason?

**Comment by rauchg** [comment]
Merged. Thanks for the fix!

**Pull request merged**
