### PR TITLE
Es6 arrow functions for anonymous functions

### PR DESCRIPTION
**Pull request by paradite**
**node v4 LTS does not have full support for the [rest parameters](http://node.green/), whereas node v6 does, I am waiting for node v6 to become more popular to continue working on this PR**

This PR refactors existing codebase's anonymous functions into es6 arrow functions.
A new `dist` folder holds the babel transpiled es5 code which is served by default by using `"main": "./dist/index",` in `package.json` (there is no `index.js` for this repo so `package.json` defines the entry point)

Due to the new Lexical `arguments` (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
I have changed one use of `var args = Array.prototype.slice.call(arguments);` into rest parameters syntax `...args`. 
see: https://github.com/nus-fboa2016-si/socket.io/blob/ae6379f8d60b275e9fc2bbb2de6639e11a3b180d/lib/socket.js#L346

However, the rest parameters feature is behind the staging flag for node.js:
https://nodejs.org/en/docs/es6/#which-features-are-behind-the-es_staging-flag
So the test for current code will fail on node due to syntax error, one way is to test using the `harmony` flag: 

```
node --harmony `which gulp` test && node --harmony `which gulp` test-compat
```

For the sake of simplicity, I have removed the tests for the current code and only test the compat version of the code transpiled by `babel`

### CODE REVIEW

**Comment by amit3vr** [comment]
This would be bad news for developers who aren't using the latest node.js version/don't support ES6 syntax. :cry: 

This PR might make the code much readable, but your'e risking compatibility issues.

Good job anyways.

_btw i'm looking forward for your response to my comment. i'm really excited to here more opinions about this issue, and hopefully start a discussion around this subject._

**Comment by paradite** [comment]
Yup, I think I will wait until node v6 to become more mainstream before updating this PR.

**Comment by amit3vr** [comment]
Haha. I don't think it's all about mainstream-ness (is that a word?) - but it's more about taking care of as much edge cases as possible.
This is why the trade-of of compatibility for readability (with no additional benefits) seems unnecessary.

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io/commit/3d760b71d7ee480dfab4b9f336a5d90d970c6b3f (finally). Thanks!

**Pull request closed without merging**
