### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [x] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

No badge

### New behaviour

Badge that displays the npm install size

### CODE REVIEW

**Comment by oke11o** [comment]
Hi! Gays.

Great PR.

I approve this.

**Comment by darrachequesne** [comment]
I'm not sure we really need yet another badge. Following the bundle size of the client could be interesting though, does packagephobia support this?

**Comment by styfle** [comment]
There is another tool to determine the webpack bundle size of a package called [Bundle Phobia](https://bundlephobia.com/result?p=socket.io)

I would argue that the [Package Phobia](https://packagephobia.now.sh/result?p=socket.io) size is interesting because it shows how durastic the change in dependencies was in v2.1.0

If you bundle your own file, you can use [badge-size](https://github.com/ngryman/badge-size) to display the size of a single file.

All of these options are available on badgen.net like so:

- https://badgen.net/packagephobia/install/socket.io
- https://badgen.net/bundlephobia/minzip/socket.io
- https://badgen.net/badgesize/gzip/https://unpkg.com/socket.io/lib/client.js

**Comment by styfle** [comment]
@darrachequesne Are you aware the `socket.io` version published today jumped from 2.39 MB to 3.21 MB?

https://packagephobia.com/result?p=socket.io

**Pull request closed without merging**
