### PR TITLE
Allow to join several rooms at once

### PR DESCRIPTION
**Pull request by darrachequesne**
### The kind of change this PR does introduce

* a new feature

### New behaviour

Enable the following: 
`socket.join(['room1', 'room2']);`

Closes https://github.com/socketio/socket.io/issues/2466, closes https://github.com/socketio/socket.io/issues/2877

### CODE REVIEW

**Comment by NguyenTungs** [comment]
@darrachequesne 
Thanks a lot. So great feature that.

**Comment by NguyenTungs** [comment]
@darrachequesne .
I've tried, and upgrade version 1.7.3 
``` javascript
    "socket.io": "^1.7.3",
```

But that feature still not working.

Code here: 
``` javascript
    socket.join(['tungns1', 'tungns2', 'tungns3']); // client join
```
But i changed :
``` javascript
   for(var i = 1, length1 = 4; i < length1; i++){
             console.log('tungns'+i);
             socket.join('tungns'+i);
    }
```
Then working.
So Could you review again that feature. Thanks a lot.

**Comment by darrachequesne** [comment]
Yep, it's not released yet.

**Comment by angel1st** [comment]
@darrachequesne - since we have now ability to join multiple rooms at once, shouldn't be nice to have the same for sending a message to multiple rooms?
I know, I can manage this like that:

```
['room1', 'room2', 'room3'].forEach(room => {
  // send message to all clients in the room, but the sender
  socket.broadcast.to(room).emit('message', 'nice game');
});
```

but I guess something like:

`socket.broadcast.to(['room1', 'room2', 'room3']).emit('message', 'nice game');`

will be more handy.

**Comment by darrachequesne** [comment]
@angel1st great idea! Could you please open a PR for that?

**Pull request merged**
