### PR TITLE
Add example for private messaging in React

### PR DESCRIPTION
**Pull request by haneenmahd**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [x] other

### Current behavior
The current examples doesn't include how to implement private messaging in React.

### New behavior
This PR adds a new example for implementing private messaging in React.

### Other information (e.g. related issues)
#4580

### CODE REVIEW

**Comment by darrachequesne** [comment]
Thanks a lot @haneenmahd, I will review this as soon as possible.

**Comment by misbahkhalilaz** [comment]
Hi @everyone,

Here is a Typescript-based example app I developed in my free time. This might help someone to get a quick idea.

[Frontend](https://github.com/misbahkhalilaz/chat-room-web)
[Backend](https://github.com/misbahkhalilaz/chat-room-api)

**Comment by haneenmahd** [comment]
Can you open up a new PR linking to the issue as Typescript version?

**Comment by misbahkhalilaz** [comment]
> Can you open up a new PR linking to the issue as Typescript version?

Sure, I'll open PR this weekend soon.

**Comment by haneenmahd** [comment]
@darrachequesne, This is ready for review apart from some upgrades to the UI! The functionality is done and I need to update the UI with a better one.

**Review by sunil-9 — APPROVED** [review]
LGTM

**Comment by darrachequesne** [comment]
The "Private messaging" example needs to be rewritten, we will provide a React version of the client. Thanks!

**Pull request closed without merging**
