### PR TITLE
Exports the Namespace and Socket type v3

### PR DESCRIPTION
**Pull request by ptejada**
Exports the Namespace and Socket type from MJS wrapper

### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [x] other

### Current behavior
MJS wrapper only exports Server

### New behavior
MJS wrapper exports Server, Namaspace and Socket types 

### Other information (e.g. related issues)

I would say is a continuation of PR https://github.com/socketio/socket.io/pull/3684 and my comment there
https://github.com/socketio/socket.io/pull/3684#issuecomment-729396811

### CODE REVIEW

**Comment by darrachequesne** [comment]
May I ask what the use case is?

For TypeScript, I understand that it can be used for englobing types:

```ts
import { Namespace } from "socket.io";

class Application {
  private mainNamespace: Namespace;
}
```

But is this needed for ES modules?

**Comment by ptejada** [comment]
@darrachequesne 
Correct is only for ES module and type hinting with JSDoc. IDEs, or at least Jetbrains IDEs cannot resolve the Namaspace or Socket for autocomplete, inline docs and so on. 

Without my update
image

With the update
image

**Comment by darrachequesne** [comment]
@ptejada oh ok. Could you please open an issue in Jetbrains issue tracker then? (here I guess: https://youtrack.jetbrains.com/issues/WEB)

**Comment by ptejada** [comment]
I don't think is an issue of the IDE. What is the purpose of the `wrapper.mjs` file? 

That is the file the IDE is referencing which only exports `Server` at the moment.

I don't have enough information to log bug report for the IDE.  All I know is making the edits in the PR fixes the references.

**Review by rheh — APPROVED** [review]

**Pull request merged**
