### PR TITLE
Add support for getting clients in a given room

### PR DESCRIPTION
**Pull request by FREEZX**
Added a clients function that calls the adapter's clients function, in order to get the connected clients in a room.
Pull requests implementing the underlying adapter functions:
Redis adapter: https://github.com/Automattic/socket.io-redis/pull/15
Memory adapter: https://github.com/Automattic/socket.io-adapter/pull/5

### CODE REVIEW

**Comment by julianlam** [comment]
Was this actually merged, or just closed?

**Comment by rauchg** [comment]
We have another issue tracking this I believe. Is this why you closed @defunctzombie  ?

**Comment by defunctzombie** [comment]
I thought it was merged per the comment of "coming in next release". Sorry if that is not the case yet.

**Comment by defunctzombie** [comment]
If this is ready for merge, could the OP please cleanup the commit history.

**Comment by rauchg** [comment]
It's not though.

**Comment by panuhorsmalahti** [comment]
In which version is this feature coming?

**Comment by bcharbonnier** [comment]
Is it part of 1.3.x or not ? I can't see it in the release notes changes .....
I mean, the real question is: did the bug get fixed somehow via another PR ?

**Comment by rauchg** [comment]
It's the top priority for our next release. https://github.com/Automattic/socket.io/issues/1945

**Comment by bcharbonnier** [comment]
Great! Thanks :)

**Comment by hayksaakian** [comment]
Not clear if this is in or not? (It's been a few months since last comment on this pull)

**Comment by marksyzm** [comment]
:) It is not. I'm guessing... soon.

**Comment by luin** [comment]
Any updates on this pr?

**Comment by emadd** [comment]
+1

**Comment by austinkelleher** [comment]
+1

**Comment by wanming** [comment]
```coffeescript
getClientsInRoom: (io, roomName) ->
    ret = []
    room = io.sockets.adapter.rooms[roomName]

    return ret if !room

    for socketID of room
      ret.push(io.sockets.connected[socketID])
    ret
```

**Comment by benkaiser** [comment]
+1

**Comment by samuel281** [comment]
I'm still waiting for this feature. Is there any blocker?

**Comment by LordMajestros** [comment]
@samuel281 needs to be rebased

**Comment by Shadowstep33** [comment]
+1

**Comment by Shadowstep33** [comment]
io['sockets']['adapter']['sids'] is returning empty for me even though a client is clearly connected

**Comment by JCMais** [comment]
For anyone interested, I'm currently using the following to accomplish that:

```javascript
io.in( room ).clients(function( error, clients ) {
    if (error) throw error;
    for ( var i = 0, len = clients.length; i < len; i++ ) {
        io.sockets.connected[clients[i]].emit( 'something', {some: 'data'} );
    }
});
```

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-adapter/pull/24 and https://github.com/socketio/socket.io-redis/pull/109. Thanks!

**Pull request closed without merging**
