### PR TITLE
test with io.js

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
I just add io.js test to travis.

### CODE REVIEW

**Comment by jonhester** [comment]
:+1:

**Comment by q2dg** [comment]
+1

**Comment by nkzawa** [comment]
:+1:

**Comment by shinnn** [comment]
:+1:

**Comment by tabone** [comment]
:+1:

**Comment by nkzawa** [comment]
We wouldn't need to test on iojs anymore. Thanks for your help anyway!

**Pull request closed without merging**
