### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by xdamman**
Please merge this pull request to activate your Open Collective https://opencollective.com/socketio

### CODE REVIEW

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/socket.io/commit/0d07c47f815e2174dcafac29441123682677313c.

I'm not really fond of the `postinstall` script, so I excluded it from the merge. Is it something mandatory?

**Comment by xdamman** [comment]
It's not but it's a nice touch to ask for donations. Have you tried it? You can also pass it the `--plain` option to make it text only (and more subtle)

**Comment by darrachequesne** [comment]
@xdamman I am still not convinced that adding another dependency (something like 49 Mo if I'm not mistaken) is really necessary here. Besides, what will happen if webpack and babel and mocha and gulp... all add that postinstall script?

**Comment by xdamman** [comment]
I see 22MB on my machine. But that's highly variable depending on what other modules you already have installed in your project.

If other projects also have it, npm is smart enough to only install it once.

**Pull request closed without merging**
