### PR TITLE
fix room joining

### PR DESCRIPTION
**Pull request by helios1138**
fixes socketio/socket.io#2311

### CODE REVIEW

**Comment by nkzawa** [comment]
Recently, the type of `Socket#rooms` was changed to `Object`. I think this change would solve this issue too. Can you check that if possible?

https://github.com/socketio/socket.io/blob/master/lib/socket.js#L229

**Comment by darrachequesne** [comment]
Hi! Please correct me if I didn't understand right, but why aren't you using the callback here `Socket.prototype.join = function(room, fn)`? 

```javascript
socket.join(someRoom, function() {
  console.log(io.of('/').adapter.rooms[someRoom][socket.id]); // should always work, right?
});
```

(since `Adapter.prototype.add()` is async)

**Comment by helios1138** [comment]
@nkzawa, it does seems like *my problem* is solved, however the underlining issue is still present (even though it does not affect my end result anymore). I think potentially it can be a source of further problems.

What that means is that in the case I'm describing you will have:
```js
Socket.prototype.join = function(room, fn){
  debug('joining room %s', room);
  var self = this;
  // so *this.rooms* does not contain the *room* here
  if (this.rooms.hasOwnProperty(room)) return this;
  this.adapter.add(this.id, room, function(err){
    if (err) return fn && fn(err);
    debug('joined room %s', room);
    // but here *self.rooms* already contain the *room* sometimes
    self.rooms[room] = room;
    fn && fn(null);
  });
  return this;
};
```
Basically there is a race condition. Ideally there should be *single source of truth* regarding socket room occupancy. So the easiest way is to either make `socket.rooms` to be just a **getter** that will access `adapter.rooms` or vice versa. If for some reason it is needed to keep two separate lists (both of which can be changed by asynchronous operations), then there should be some kind of transaction logic to keep them in sync. Simple `if` condition on just one of the lists is not enough.

@darrachequesne, that's the thing - it doesn't. Async functions should **always** call the callback at the end, either with success or with error. If you look at `Socket.prototype.join()` method code, you will see that in the condition check that happens before the callback handling if the condition is `true`, it does `return this` **without calling the callback at all**. So in your code:
```js
socket.join(someRoom, function() {
  // this callback will never be actually called in the case I'm describing
  console.log(io.of('/').adapter.rooms[someRoom][socket.id]);
});
```

**Comment by darrachequesne** [comment]
My understanding is that the adapter (be it the default one, redis-adapter or any other that implements the given interface) has that *truth*. As far as I understand, the local `socket.rooms` only prevents from a superfluous round-trip to the adapter.

Now, I think you're right with the callback thing, maybe this would be better?
```javascript
if (this.rooms.hasOwnProperty(room)) {
  fn && fn(null);
  return this;
}
```

**Comment by darrachequesne** [comment]
Hi! I took the liberty to create a new PR https://github.com/socketio/socket.io/pull/2325 so that this fix could be included in the forthcoming release (which should happen soon!)

**Comment by nkzawa** [comment]
https://github.com/socketio/socket.io/pull/2325 should solve the issue, thanks @darrachequesne !

**Pull request closed without merging**
