### PR TITLE
stop prepend /# before id when no namespace

### PR DESCRIPTION
**Pull request by tw0517tw**
#2451 #2405 #2475 #2491 
This should fix break since b73d9be and #2239 

Since I'm not using namespaces, I need someone else help to check if this would break them.

### CODE REVIEW

**Comment by darrachequesne** [comment]
Shouldn't this be `nsp.name != '/' ?...` ?

Else, this might actually be a good idea, since most users actually use only one namespace (the default '/').

**Comment by tw0517tw** [comment]
Yes, it should be `nsp.name !== '/' ?...`.
Fixed.

**Comment by nkzawa** [comment]
Thanks for your PR.

We are going to change `socket.id` on client to the same format with server, which should solve the root cause of the problem.
Let me know if you have any ideas about that.

**Comment by tw0517tw** [comment]
It's good (and important?) to have same format of `socket.id` on both side (again). Hope to see that release soon.

**Comment by tgabi333** [comment]
As i see this change is not included in current (v1.4.8) release, can somebody help me out why?

**Comment by jdc20181** [comment]
Sometimes things cause issues- and are tested for functionality for the
best results before released (this is in general for any project) so they
might not have tested the feature yet. Or may think it will hurt something
else. Stay paitent :)

**Pull request merged**
