### PR TITLE
fix the text alignment in firefox

### PR DESCRIPTION
**Pull request by championswimmer**
This is just plain strange, but using fotn size above 150% makes the alignment got crazy on firefox. No idea at all why and how. 

Check http://imgur.com/TRdhV8Y to have an idea of what I am talking about.

### CODE REVIEW

**Comment by nkzawa** [comment]
Umm, don't know why but I can't reproduce the issue. Firefox on OSX.

**Comment by championswimmer** [comment]
I can still reproduce this. 

Firefox 41.0.2, Linux x64

**Comment by championswimmer** [comment]
I can't fathom, at all, why though

**Comment by nkzawa** [comment]
Fixed via https://github.com/socketio/socket.io/pull/2477. Thanks!

**Pull request closed without merging**
